sudo: false
language: node_js
node_js:
- "8.11.4"
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn lint
after_success:
  - yarn release
  - yarn global add @immowelt/docker-publish
  - docker login -u=$IMMO_DOCKER_USER -p=$IMMO_DOCKER_PASS
  - DEBUG=*immowelt* docker-publish --tags=https://api.github.com/repos/ImmoweltGroup/lighthouse-ci/tags --image=immowelt/lighthouse-ci
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
